/** @deprecated Use lib/catalog.ts — kept for import compatibility */
export {
  getInventory,
  getInventoryItem,
  getAvailableInventory,
  getSellableItems,
  getSellableItem,
  getAvailableSellable,
  searchSellableItems,
  initializeAppData,
  initializeMenu,
  initializeDemoInventory,
  initializeDemoData,
  createInventoryItem,
  createMenuAndStock,
  restockItem,
  deductStock,
  isLowStock,
  canFulfillQuantity,
  getAvailableStockForOrder,
  calcStockNeeded,
  logActivity,
  getActivityLog,
  deleteInventoryItem,
  updateInventoryItem,
  restoreStock,
  resetAllShopData,
} from "./catalog";
export {
  getStockAdditions,
  getStockAdditionsInRange,
  getTodayStockAdditions,
  logStockAddition,
} from "./stock-additions";
